# Generated by Django 4.2.7 on 2023-11-15 13:25

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
